export const Language = {
    fa: {
        login_title: "ورود به حساب کاربری",
        label_username: "نام کاربری",
        label_password: "رمز عبور",
        login: "ورود",
        name: "حسین نهالی",
        roleAdmin: "مدیر",
        searchPlaceholder: "جستجو...",
        totalParticipant: "مجموع شرکت کنندکان",
        totalParticipantNumber: "72",
        developersTitle: "برنامه نویسان این پروژه",
        status: 'وضعیت',
        home: 'خانه',
        home_tooltip: 'خانه',
        list_test: 'لیست آزمون ها',
        create_test: 'ایجاد آزمون',
        list_users: 'لیست کاربران',
        good_morning: 'صبح بخیر',
        good_afternoon: 'عصر بخیر',
        good_night: 'شب بخیر',
        status_desc_title: {
            today: 'امروز',
            person: 'نفر',
            in_test: 'در آزمون',
            participated: 'شرکت کردند'
        },
        personality_test: 'تیپ شخصیتی',
        participants: 'شرکت کنندگان',
        person_27: '27 نفر',
        tests: 'آزمون ها',
        active_tests_30: '30 آزمون فعال',
        free_host_space: 'فضای آزاد هاست',
        mg_3000: '3000 مگابایت',
        mg_500: '500 مگابایت',
        used_host_space: 'فضای استفاده شده هاست',
        our_instagram: 'اینستاگرام ما',
        our_telegram: 'تلگرام ما',
        our_whatsapp: 'واتساپ ما',
        setting: 'تنظیمات',
        editing_information: 'ویرایش اطلاعات',
        display_name: 'نام نمایشی',
        desc_upload: 'برای آپلود تصویر در این کادر کلیک کرده یا آن رو کشیده و اینجا رها کنید',
        edit_profile_picture: 'ویرایش عکس پروفایل',
        drop_file_here: 'فایل را اینجا رها کنید',
        size_file: 'حجم فایل',
        name_file: 'نام فایل',
        save: 'ذخیره',
        select_image_only: 'لطفا فقط فایل تصویر انتخاب کنید',
        delete_selected_items: 'حذف موارد انتخاب شده',
        confirm_delete: 'آیا از حذف اطمینان دارید ؟',
        yes: 'بله',
        no: 'خیر',
        desc_create_test: 'توجه داشته باشید پس از ایجاد لینک آزمون در اختیار شما قرار خواهد گرفت.'
    },
    en: {}
}